import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import '../public/css/ServicePage.css'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

      <body className={inter.className}>
        <Navbar />

        {children}
        <Footer/>
      </body>
    </html>
  );
}
